language: php

php: ["5.5", "5.6", "hhvm"]

matrix:
    allow_failures: [{"php": "5.6"}, {"php": "hhvm"}]
    fast_finish: true

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.5
    - secure: "EAWM4sajWkbhTrYqXv9DQ2qaFrOM9ed8TiApzojgEo5/jRQVfS1rb9jfyOa1mLdWqogTKltflEqHiQCWpomi56nqmNgS9cfzpNYpveTJuM7auk6xurPXarDUCbt56mJgIdhcha+tbLrBikvpi3mZn0pM2QQs02lEFzan9G1iaWc="

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
