language: php

php: ["5.5", "5.6", "hhvm", "hhvm-nightly"]

matrix:
    allow_failures: [{"php": "hhvm"}, {"php": "hhvm-nightly"}]
    fast_finish: true

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.6
    - secure: "TT3JxfB6fbd21cfHoHu9N4Eh9Vly4sks1ZYiIbtNvBLx2IZUJoV1NKdx/G04hNk31730AH1tEvYS2cVDqtm07FprqXnaHwF8dVfg2ua0SjyAMJxy558DIsUGUKuSuPAkp/mDEq3qH+PlWbeUA3GkzVF7dYKgbeMFhh+8SFRZPrM="

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
