var tree = [["Icecave",,"",
                [["Lace","Icecave\/Lace.html","",
                [["Cache","Icecave\/Lace\/Cache.html","",
                [["CacheDsnParser","Icecave\/Lace\/Cache\/CacheDsnParser.html","",
                [        ]],["CacheHandlerInterface","Icecave\/Lace\/Cache\/CacheHandlerInterface.html","",
                [        ]],["CacheVisitorInterface","Icecave\/Lace\/Cache\/CacheVisitorInterface.html","",
                [        ]],["RedisHandler","Icecave\/Lace\/Cache\/RedisHandler.html","",
                [        ]]        ]],["Database","Icecave\/Lace\/Database.html","",
                [["DatabaseDsnParser","Icecave\/Lace\/Database\/DatabaseDsnParser.html","",
                [        ]],["DatabaseHandlerInterface","Icecave\/Lace\/Database\/DatabaseHandlerInterface.html","",
                [        ]],["DatabaseVisitorInterface","Icecave\/Lace\/Database\/DatabaseVisitorInterface.html","",
                [        ]],["MySqlHandler","Icecave\/Lace\/Database\/MySqlHandler.html","",
                [        ]],["PostgresHandler","Icecave\/Lace\/Database\/PostgresHandler.html","",
                [        ]],["SqliteHandler","Icecave\/Lace\/Database\/SqliteHandler.html","",
                [        ]]        ]],["HandlerInterface","Icecave\/Lace\/HandlerInterface.html","",
                [        ]],["PackageInfo","Icecave\/Lace\/PackageInfo.html","",
                [        ]],["ParserInterface","Icecave\/Lace\/ParserInterface.html","",
                [        ]]        ]]        ]]        ]

