var tree = [["Icecave",,"",
                [["Lace","Icecave\/Lace.html","",
                [["Handler","Icecave\/Lace\/Handler.html","",
                [["Cache","Icecave\/Lace\/Handler\/Cache.html","",
                [["CacheHandlerInterface","Icecave\/Lace\/Handler\/Cache\/CacheHandlerInterface.html","",
                [        ]],["CacheVisitorInterface","Icecave\/Lace\/Handler\/Cache\/CacheVisitorInterface.html","",
                [        ]],["RedisHandler","Icecave\/Lace\/Handler\/Cache\/RedisHandler.html","",
                [        ]]        ]],["Database","Icecave\/Lace\/Handler\/Database.html","",
                [["DatabaseHandlerInterface","Icecave\/Lace\/Handler\/Database\/DatabaseHandlerInterface.html","",
                [        ]],["DatabaseVisitorInterface","Icecave\/Lace\/Handler\/Database\/DatabaseVisitorInterface.html","",
                [        ]],["MySqlHandler","Icecave\/Lace\/Handler\/Database\/MySqlHandler.html","",
                [        ]],["PostgresHandler","Icecave\/Lace\/Handler\/Database\/PostgresHandler.html","",
                [        ]],["SqliteHandler","Icecave\/Lace\/Handler\/Database\/SqliteHandler.html","",
                [        ]]        ]],["HandlerInterface","Icecave\/Lace\/Handler\/HandlerInterface.html","",
                [        ]]        ]],["CacheDsnParser","Icecave\/Lace\/CacheDsnParser.html","",
                [        ]],["DatabaseDsnParser","Icecave\/Lace\/DatabaseDsnParser.html","",
                [        ]],["PackageInfo","Icecave\/Lace\/PackageInfo.html","",
                [        ]],["ParserInterface","Icecave\/Lace\/ParserInterface.html","",
                [        ]]        ]]        ]]        ]

